# Instructions here: https://snakemake.readthedocs.io/en/stable/executing/cli.html
executor: local
jobs: 20
conda-prefix: .snakemake/conda
rerun-incomplete: true
keep-going: true
latency-wait: 60

# No wall time information given. This might or might not work on your cluster. If not, specify the resource runtime in your rule or as a reasonable default via --default-resources.
# TBD
#
default-resources:
    mem_mb: 5000

set-threads:
    downloadData: 2
    generateAdata: 8
    runStardist: 8
    runBin2cell: 8
    test: 2
    runRCTD: 16
    runAdataMerge: 8

set-resources:
    downloadData: 
        mem_mb: 8000
        mem_gb: 8
    generateAdata:
        mem_mb: 16000
        mem_gb: 16
    runStardist:
        mem_mb: 64000
        mem_gb: 64
    runBin2cell:
        mem_mb: 64000
        mem_gb: 64
    runRCTD: 
        mem_mb: 64000 # To be decided
        mem_gb: 64
    runAdataMerge:
        mem_mb: 16000
        mem_gb: 16
